theme: jekyll-theme-minimal

title: PyStack't Documentation
description: "Real-life data for object-centric processing mining"
logo: /images/pystackt_logo_black_circle_small.png

paper_url: https://ceur-ws.org/Vol-4032/paper-28.pdf
paper_title: "PyStack’t: Real-Life Data for Object-Centric Process Mining"
